### ISSUE TITLE
[KF Mgmt][CR]增加导出统计功能，查询增加时间范围选择和修改导出模板

### ISSUE THREAD

**Issue by Changchun-lin** [csdperic/csdp-support#17]
列表查询页面
增加按照登记时间（registered date）时间段查询和导出，页面增加开始时间和结束时间的日期框。

导出模板修改
1.增加导出时间段在标题上
2.两个sheet合并后增加hot case列
3.导出按照Domain,ImpactedProduct 2个字段排序，Domain为第一排序，ImpactedProduct为第二排序
4.模板保留所有列
5.模板字段顺序已修改，见附件
6.按照domain和impacted product实现数目的统计,具体详细数据List和数目统计分开2 sheet显示

附件：
[Known fault List.zip](https://github.com/csdperic/csdp-support/files/481549/Known.fault.List.zip)

**Comment by Ge-Fei** [comment]
已完成

**Comment by richardzhai01** [comment]
长春，需要进行验证
