### ISSUE TITLE
IBase 菜单权限调整

### ISSUE THREAD

**Issue by Changchun-lin** [csdperic/csdp-support#18]
需要对ne type& dict，Ne warranty,HW Management这3个模块进行调整。

以ne type& dict为例。
下图对于现在77上红色框里面的需要合并到一个文件夹下，这个文件夹与SW type同级。ne type& dict的5个文件夹对应管理页面上5个页签。方便分配权限时对应区分是属于哪模块下面。

![image](https://cloud.githubusercontent.com/assets/21305906/18702177/16bc9f26-8013-11e6-9e83-ecd5380c1e2a.png)

![image](https://cloud.githubusercontent.com/assets/21305906/18702279/9241db16-8013-11e6-8172-d5e83306e96e.png)

其他2个模块也是需要类似的操作

![image](https://cloud.githubusercontent.com/assets/21305906/18702340/dfd21a30-8013-11e6-88c5-3a9de9030254.png)

![image](https://cloud.githubusercontent.com/assets/21305906/18702376/0943bac2-8014-11e6-8d7a-c8061b1791a1.png)

备注：此功能正式升级还需要重新设置角色里面的相对应的权限。

**Comment by Ge-Fei** [comment]
已调整
