### ISSUE TITLE
FOA info需要改进的地方

### ISSUE THREAD

**Issue by ekeekee** [csdperic/csdp-support#2]
Export 出来的excel表格式需要改进，column的排序需要调整一下以方便查看，跟CSP Foa info页面上的排序一致。
![image](https://cloud.githubusercontent.com/assets/21305932/18073507/2e003868-6e99-11e6-81d8-97e672aff087.png)

**Comment by ekeekee** [comment]
...

**Comment by richardzhai01** [comment]
你的意思是按照你帖出来的图的排列顺序， 同排列export出来的excel吗？

**Comment by ekeekee** [comment]
跟CSP Foa info页面上的排序一致。我贴的图就是CSP页面上的

**Comment by ekeekee** [comment]
77测试通过
