### ISSUE TITLE
检查发现sumOrderService类sql语句查询报错，原因没找到status字段/属性。

### ISSUE THREAD

**Issue by Changchun-lin** [csdperic/csdp-support#30]
如图,原因是没找到status字段/属性。

![image](https://cloud.githubusercontent.com/assets/21305906/19229949/f18f176a-8f03-11e6-9d91-f6c056a8e955.png)

**Comment by Ge-Fei** [comment]
这个status字段是有的。可能是给你们那边的人动了数据库，删掉了，你问问谁动了，恢复就好了

**Comment by richardzhai01** [comment]
林长春需要跟进

**Comment by Changchun-lin** [comment]
已增加字段，修改完成。
