### ISSUE TITLE
System-->Param模块进不去

### ISSUE THREAD

**Issue by Changchun-lin** [csdperic/csdp-support#32]
点击Param菜单,前台报system error

 #![image](https://cloud.githubusercontent.com/assets/21305906/19300343/5b15ab66-908c-11e6-8a17-fd9183e56a9b.png)

后台报错如下
![image](https://cloud.githubusercontent.com/assets/21305906/19300375/86bf93bc-908c-11e6-9b80-f0bab3565927.png)

**Comment by Ge-Fei** [comment]
本地呈现不出来，有什么方式可以呈现出来？

**Comment by ekeekee** [comment]
是74applicationContext-quartz.xml文件没有配置quartzManagerBean导致的，已经修复上线。
Close.
