### ISSUE TITLE
ibasic的ne Manegement查询框没有找到CMJS的operator

### ISSUE THREAD

**Issue by Changchun-lin** [csdperic/csdp-support#35]
ibasic的ne Manegement界面的查询框没有显示出CMJS的operator，但operator表和网元数据都是有CMJS。

**Comment by Ge-Fei** [comment]
如何重现？本地没有这个问题。
![image](https://cloud.githubusercontent.com/assets/15045906/19589866/61dd2cdc-97a1-11e6-992d-96c17db41276.png)

**Comment by Changchun-lin** [comment]
现在再试是可以的，先关闭吧，下次出现再提出。
