### ISSUE TITLE
ibase update SGSN log error

### ISSUE THREAD

**Issue by Changchun-lin** [csdperic/csdp-support#41]
![image](https://cloud.githubusercontent.com/assets/21305906/19711720/450ed55c-9b6a-11e6-81a2-3a61c0dfcee0.png)

**Comment by Ge-Fei** [comment]
把原数据文件发过来看看，看错误是数据文件里面的数据有问题。

**Comment by Changchun-lin** [comment]
已发

**Comment by Ge-Fei** [comment]
数据有问题很明显的错误：
1、Operator: csp没有CMTEST 这个operator
![image](https://cloud.githubusercontent.com/assets/15045906/19757582/4933685e-9c56-11e6-8f87-f785d9bd2987.png)
2、csp 没有FO 这个TRAFFIC_COVERED_CITY 和 DEVICE_BELONG_TO_CITY 所以报错。

|NodeBasic:TRAFFIC_COVERED_CITY:FO|NodeBasic:DEVICE_BELONG_TO_CITY:FO|

要解决这个问题：需要在csp建CMTEST的operator，建FO的TRAFFIC_COVERED_CITY 和DEVICE_BELONG_TO_CITY

**Comment by Changchun-lin** [comment]
这个建city和operator的操作有客户可以做的管理界面吗？我看以后还会遇到这种情况。
数据库表是t_sys_operator ，city是在哪个表？

**Comment by Changchun-lin** [comment]
FO是ibase那边上传log的时候要改为FOSHAN,这个不用增了，至于CMTEST看看是不是测试的

**Comment by Changchun-lin** [comment]
CMTESTlog那边已设置不上传。问题解决
