### ISSUE TITLE
iBase NE Management Import template调整

### ISSUE THREAD

**Issue by ekeekee** [csdperic/csdp-support#49]
将OMC的位置调制到SDM前面一位；
![image](https://cloud.githubusercontent.com/assets/21305932/19923161/18aa214e-a121-11e6-925d-b86944f1b429.png)

**Comment by Ge-Fei** [comment]
1、ne management import 你直接调整导入模板即可
2、Export本地 已经将OMC位置调整到SDM。
![image](https://cloud.githubusercontent.com/assets/15045906/19953661/81a6f7aa-a1ab-11e6-9489-d182145ebf9d.png)

**Comment by ekeekee** [comment]
已经改了，Assiganses 给我的.

**Comment by ekeekee** [comment]
我这个直接改模版，改不了的，这个Export的Excel是代码生成的，要改生成的那块代码
