### ISSUE TITLE
Package management 需要的改进 FOA report

### ISSUE THREAD

**Issue by ekeekee** [csdperic/csdp-support#5]
1. Assign Foa时，在Assign的信息增加ne type,system version,Operator要显示;
2. update sw package-Foa report 跳转到FOA Info页面时，需要把FOA Info的基本信息带过去;
3. Certification Code增加附件导入功能

**Comment by Ge-Fei** [comment]
已完成

**Comment by ekeekee** [comment]
1.Assign Foa时，在Assign的信息增加ne type,system version,Operator要显示，测试失败Operator没有显示出来：
![image](https://cloud.githubusercontent.com/assets/21305932/18905297/0254d44a-8595-11e6-9d3d-14065a090d82.png)

![image](https://cloud.githubusercontent.com/assets/21305932/18905306/0e32c006-8595-11e6-94b9-f5fca0a1647f.png)

2.update sw package-Foa report 跳转到FOA Info页面时，需要把FOA Info的基本信息带过去，测试通过；
3.Certification Code增加附件导入功能，测试通过，保留疑问：
![image](https://cloud.githubusercontent.com/assets/21305932/18905428/b98aed5c-8595-11e6-9a25-9779fee756e2.png)
Certification Code允许重复的Code？

**Comment by Ge-Fei** [comment]
已经修改，Code不能重复。测试看看
