### ISSUE TITLE
iBase NE Management Advanced Search CR

### ISSUE THREAD

**Issue by ekeekee** [csdperic/csdp-support#51]
1.iBase NE Management Advanced Search功能，Change CNS后，OSS，Operator，Traffic Coverd City，Device Belong City，Domain需要重新选择并按照CNS进行筛选;
![image](https://cloud.githubusercontent.com/assets/21305932/19923352/e8e67c5e-a121-11e6-8b4e-b3e12f162e09.png)

**Comment by Ge-Fei** [comment]
魏思勇 To：已解决

**Comment by ekeekee** [comment]
尴尬，这个是我自己Assiganees给自己的，我已经做了这个补丁。
