### ISSUE TITLE
[CR]CSP中NE Management---Advanced Search---SW----需要增加Status的功能

### ISSUE THREAD

**Issue by Changchun-lin** [csdperic/csdp-support#55]
需要增加Status的功能 (设置默认值 = Loaded)

因为搜索网元补丁包时，如果没有状态选择，所有含有Replaced补丁包的网元也出现在搜索结果中。如，当需要将CMGD BSC G12A IPA11   56个网元筛选出来时，得到的结果有600多（所有Status都有）。

 
![image](https://cloud.githubusercontent.com/assets/21305906/20509480/03800dc8-b0a4-11e6-93e1-dd50bb4037e1.png)

![image](https://cloud.githubusercontent.com/assets/21305906/20509485/0b98a934-b0a4-11e6-9ab9-a71d971b1aa0.png)

**Comment by Ge-Fei** [comment]
已处理
